const livros = [
    {
        id: 1,
        nome: "A Sombra do Vento",
        autor: "Carlos Ruiz Zafón",
        categoria: "Suspense",
        paginas: 464,
        recomenda: true,
        leu: true,
    },
    {
        id: 2,
        nome: "O Jogo do Anjo",
        autor: "Carlos Ruiz Zafón",
        categoria: "Suspense",
        paginas: 416,
        recomenda: true,
        leu: true,
    },
    {
        id: 3,
        nome: "O Prisioneiro do Céu",
        autor: "Carlos Ruiz Zafón",
        categoria: "Suspense",
        paginas: 246,
        recomenda: true,
        leu: true,
    },
    {
        id: 4,
        nome: "A Menina Que Roubava Livros",
        autor: "Markus Zusak",
        categoria: "Ficção histórica",
        paginas: 468,
        recomenda: true,
        leu: true,
    },
    {
        id: 5,
        nome: "Estrutura de Dados e Algoritmos com Javascript",
        autor: "Loiane Groner",
        categoria: "Tecnologia",
        paginas: 408,
        recomenda: true,
        leu: false,
    },
    {
        id: 6,
        nome: "The Lean Startup",
        autor: "Eric Ries",
        categoria: "Tecnologia",
        paginas: 336,
        recomenda: true,
        leu: true,
    },
    {
        id: 7,
        nome: "O Diário da Juventude",
        autor: "Daisaku Ikeda",
        categoria: "Budismo",
        paginas: 600,
        recomenda: true,
        leu: true,
    },
    {
        id: 8,
        nome: "Espaço e Vida Eterna",
        autor: "Daisaku Ikeda",
        categoria: "Budismo",
        paginas: 278,
        recomenda: true,
        leu: true,
    },
    {
        id: 9,
        nome: "Doutor Jivago",
        autor: "Boris Pasternak",
        categoria: "Épico",
        paginas: 616,
        recomenda: true,
        leu: true,
    },
]

module.exports = livros